### ISSUE TITLE
Unsemantic <i> tags

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/charles-dickens_a-tale-of-two-cities#2]
The 'scrap of a note' at the end of chapter-2-9 should probably be placed within a blockquote with semantic z3998:letter. That would also allow you to remove the non-semantic `<i>` and instead target the blockquote in CSS with font-style:italic. Although I'm not sure it needs italics, even if the page scans do.

And the reference to the letter E in chapter-3-10 para 34 should be semantically tagged like this:

`<i epub:type="z3998:grapheme">E</i>`

**Comment by vr8hub** [comment]
I should have caught the italic on the E, but I've never seen any mention of the z3998:grapheme and it's not mentioned anywhere on the web site. Filed away for the future. Thanks!

I just had another instance of that exact kind of note in the Carlyle I'm working on, I asked about it, and Alex it was fine to leave it and leave without semantics.

**Comment by drgrigg** [comment]
I used the z3998:grapheme quite a few times when I was doing the Sherlock Holmes short stories, which is why I am familiar with it. It's worth having a read through the Z3998 semantics vocabulary here: http://www.daisy.org/z3998/2012/vocab/structure/

**Comment by vr8hub** [comment]
I see now that I _did_ catch the italic on the E. So it was just the never mentioned single-letter epub type I wasn't aware of.
I have. I have not, however, memorized it. Nor am I planning to. :)
Fixed.
